# ==================================================
# SYSTEM CONTRACT
# --------------------------------------------------
# System: MissionData
#
# Role:
# Stores the live state of a single active mission instance in a province.
# One MissionData is created per spawned mission and stored in
# GameState.active_missions (keyed by mission_instance_id).
#
# MissionData is distinct from the mission template in MissionLibrary.
# The template defines what a mission is; MissionData tracks its live state.
#
# Allowed Interactions:
# - GameState (registry)
# - MissionResolver (spawns, advances, resolves)
# - ProvinceData (province holds mission_instance_id references)
# - LeaderData (leader holds mission_instance_id when assigned)
#
# Forbidden Responsibilities:
# - Must not execute gameplay logic
# - Must not queue orders
# - Must not interact with UI directly
#
# Game Phase:
# Both
# ==================================================

extends Resource
class_name MissionData

# --------------------------------------------------
# IDENTITY
# --------------------------------------------------

# Unique runtime ID for this mission instance (e.g. "mission_0042")
# Generated by MissionResolver on spawn. Not the same as template_id.
@export var instance_id: String = ""

# The template this mission was generated from (e.g. "bandit_warlord")
# Maps to MissionLibrary.get_template(template_id)
@export var template_id: String = ""

# Human-readable name pulled from template at spawn time (cached for UI)
@export var display_name: String = ""

# --------------------------------------------------
# LOCATION & FLAVORING
# --------------------------------------------------

@export var province_id: int = -1
@export var biome: String = "plains"   # biome of origin province at spawn time

# --------------------------------------------------
# MISSION TYPE
# --------------------------------------------------
# Type: hunt_capture | hunt_eliminate | hunt_rescue | skirmish | treasure | elite | tutorial
# Risk: very_low | low | medium | high
@export var mission_type: String = ""
@export var risk_level: String = "medium"

# --------------------------------------------------
# TIMING
# --------------------------------------------------

# Turns until this mission expires if nobody is assigned
# Set at spawn from template duration range (2–4 turns)
@export var duration_remaining: int = 3

# Slot index within the province (0 or 1) — used to write back cooldown on expiry
@export var slot_index: int = 0

# --------------------------------------------------
# ASSIGNMENT STATE
# --------------------------------------------------

# -1 = unassigned | leader.id = assigned
@export var assigned_leader_id: int = -1

# Travel phase countdown — set to 1 when leader is assigned
# Counts down on each execute: 1 → 0 triggers battle
@export var travel_turns_remaining: int = 0

# Phase: available | travelling | battle_ready | completed | expired
@export var phase: String = "available"

# --------------------------------------------------
# BATTLE TEMPLATE (scaled at assignment time)
# --------------------------------------------------
# Populated by MissionResolver._build_battle_template() when the leader is assigned.
# Contains the enemy force dict ready to pass into the battle setup_dict.
# Format mirrors the attacker_leaders / defender_leaders structure used in
# the existing tactical battle system.
@export var battle_template: Dictionary = {}

# --------------------------------------------------
# REWARD TABLE (resolved after battle)
# --------------------------------------------------
# Populated from template at spawn. Contains:
# { "xp_min": int, "xp_max": int, "item_chance": float,
#   "gold_min": int, "gold_max": int,
#   "unit_capture": bool, "leader_recruit": bool, "gem_chance": float }
@export var reward_table: Dictionary = {}

# --------------------------------------------------
# RESULT (written after battle resolves)
# --------------------------------------------------
# "none" | "win" | "loss"
@export var result: String = "none"


# --------------------------------------------------
# HELPERS
# --------------------------------------------------

func is_available() -> bool:
	return phase == "available" and assigned_leader_id == -1

func is_assigned() -> bool:
	return assigned_leader_id >= 0

func is_battle_ready() -> bool:
	return phase == "battle_ready"

func is_expired() -> bool:
	return phase == "expired"

func get_type_display() -> String:
	match mission_type:
		"hunt_capture":   return "Hunt — Capture"
		"hunt_eliminate": return "Hunt — Eliminate"
		"hunt_rescue":    return "Hunt — Rescue"
		"skirmish":       return "Skirmish"
		"treasure":       return "Treasure"
		"elite":          return "Elite"
		"tutorial":       return "Tutorial"
	return mission_type.capitalize()

func get_risk_display() -> String:
	match risk_level:
		"very_low": return "Very Low"
		"low":      return "Low"
		"medium":   return "Medium"
		"high":     return "High"
	return risk_level.capitalize()
